### ISSUE TITLE
Push rejected, failed to compile Python app.

### ISSUE THREAD

**Issue by siznad** [ameerbadri/twilio-taskrouter-realtime-dashboard#6]
I am trying to deploy this to Heroku but it is failing.

-----> Python app detected
-----> Installing python-3.6.12
-----> Installing pip 20.1.1, setuptools 47.1.1 and wheel 0.34.2
-----> Installing SQLite3
-----> Installing requirements with pip
       Collecting certifi==2017.7.27.1
         Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349 kB)
       Collecting chardet==3.0.4
         Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
       Collecting click==6.7
         Downloading click-6.7-py2.py3-none-any.whl (71 kB)
       Collecting flask>=0.12.3
         Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
       Collecting gunicorn==19.7.1
         Downloading gunicorn-19.7.1-py2.py3-none-any.whl (111 kB)
       Collecting idna==2.5
         Downloading idna-2.5-py2.py3-none-any.whl (55 kB)
       Collecting itsdangerous==0.24
         Downloading itsdangerous-0.24.tar.gz (46 kB)
       Collecting Jinja2>=2.10.1
         Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
       Collecting MarkupSafe==1.0
         Downloading MarkupSafe-1.0.tar.gz (14 kB)
           ERROR: Command errored out with exit status 1:
            command: /app/.heroku/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dtjpifo5/MarkupSafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dtjpifo5/MarkupSafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-phy1t_qh
                cwd: /tmp/pip-install-dtjpifo5/MarkupSafe/
           Complete output (5 lines):
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/pip-install-dtjpifo5/MarkupSafe/setup.py", line 6, in <module>
               from setuptools import setup, Extension, Feature
           ImportError: cannot import name 'Feature'
           ----------------------------------------
       ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by thosi-yamada** [comment]
me too

**Comment by Lamb11** [comment]
me too

**Comment by theviktor** [comment]
Too!

**Comment by Prerit-Bhagat** [comment]
any one with solution ?
